site_name: Stag.io

repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G3_stag.io
repo_name: 'Stag.io'

theme:
  name: material
  language: 'pt'
  features:
          - navigation.tabs
  logo: 'assets/icons/logo.png'
  favicon: 'assets/icons/logo-white.png'
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Base:
    - Projeto Não Orientado a Abordagens Específicas:
      - Design Sprint:
        - Documento: Base/PNOAE/DesignSprint/Documento.md
        - Prototipação:
          - Protótipo de Baixa Fidelidade: Base/PNOAE/DesignSprint/Prototipacao/PrototipoBaixaFidelidade.md
          - Planejamento da Avaliação do Protótipo de Alta Fidelidade: Base/PNOAE/DesignSprint/Prototipacao/PlanejAvalProtAltaFidelidade.md
          - Resultados da Avaliação do Protótipo de Alta Fidelidade: Base/PNOAE/DesignSprint/Prototipacao/AvalProtAltaFidelidade.md
          - Protótipo de Alta Fidelidade: Base/PNOAE/DesignSprint/Prototipacao/PrototipoAltaFidelidade.md
      - Requisitos:
        - Pré-Rastreabilidade:
          - 5W2H: Base/PNOAE/Requisitos/PreRastreabilidade/5W2H.md
          - Mapa Mental: Base/PNOAE/Requisitos/PreRastreabilidade/MapaMental.md
          - Rich Picture: Base/PNOAE/Requisitos/PreRastreabilidade/RichPicture.md
          - Causa e Efeito: Base/PNOAE/Requisitos/PreRastreabilidade/CausaEfeito.md
        - Rastreabilidade:
          - Matriz de Rastreabilidade: Base/PNOAE/Requisitos/Rastreabilidade/MatrizRastreabilidade.md
        - Elicitação:
          - Brainstorming: Base/PNOAE/Requisitos/Elicitacao/Brainstorming.md
          - StoryBoards: Base/PNOAE/Requisitos/Elicitacao/StoryBoards.md
          - Introspecção: Base/PNOAE/Requisitos/Elicitacao/Introspeccao.md
        - Priorização:
          - MoSCoW: Base/PNOAE/Requisitos/Priorizacao/Moscow.md
        - Modelagem:
          - Especificação Suplementar: Base/PNOAE/Requisitos/Modelagem/EspecificacaoSuplementar.md
          - Léxico: Base/PNOAE/Requisitos/Modelagem/Lexico.md
    - Processos, Metodologias e Abordagens:
      - Metodologia: Base/PMA/Metodologia.md
      - Modelagem BPMN: Base/PMA/ModelagemBPMN.md
    - Iniciativas Extras:
      - Backlog do Produto:
        - Histórias de Usuário:
          - Metodologia: Base/IE/BacklogProduto/HistoriasUsuario/Metodologia.md
          - Épicos:
            - Épico 00: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico00.md
            - Épico 01: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico01.md
            - Épico 02: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico02.md
            - Épico 03: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico03.md
            - Épico 04: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico04.md
            - Épico 05: Base/IE/BacklogProduto/HistoriasUsuario/Epicos/Epico05.md

      - Riscos:
        - TAP: Base/IE/Riscos/TAP.md
        - Plano de Gerenciamento de Risco: Base/IE/Riscos/PlanoGerenciamentoRisco.md
      - Personas: Base/IE/Personas.md
      - Valor, Custo e Risco: Base/IE/ValorCustoRisco.md
    - Reuniões:
      - Atas:
        - 21/01/2022: Base/Reunioes/Atas/Ata1.md
        - 24/01/2022: Base/Reunioes/Atas/Ata2.md
        - 25/01/2022: Base/Reunioes/Atas/Ata3.md
        - 26/01/2022: Base/Reunioes/Atas/Ata4.md
      - Sprint:
        - Planejamento: Base/Reunioes/Sprint/Planejamento.md
        - Revisão: Base/Reunioes/Sprint/Revisao.md
    - Apresentação: Base/Apresentacao.md
  - Modelagem:
    - Projeto orientado a abordagens tradicionais:
      - Notação UML - Diagramas estáticos:
        - Diagrama de Classes: Modelagem/ME/DiagramaDeClasse.md
        - Diagrama de Pacotes: Modelagem/ME/DiagramaDePacotes.md
        - Diagrama de Componentes: Modelagem/ME/DiagramaDeComponentes.md
      - Notação UML - Diagramas dinâmicos:
        - Diagrama de Sequência: Modelagem/MD/DiagramaDeSequencia.md
        - Diagrama de Comunicação: Modelagem/MD/DiagramaDeComunicacao.md
        - Diagrama de Atividades: Modelagem/MD/DiagramaDeAtividades.md
        - Diagrama de Estados: Modelagem/MD/DiagramaDeEstados.md
      - Modelagem ágil: 
        - Backlog do produto: Modelagem/MA/backlog.md
        - Critérios de aceitação do backlog do produto: Modelagem/MA/CriteriosDeAceitacao.md
    - Iniciativas extras:
      - Casos de uso: Modelagem/IE/CasosDeUso.md
      - Modelagem de dados: Modelagem/IE/ModelagemDeDados.md
    - Reuniões:
      - Atas:
        - 11/02/2022: Modelagem/Reunioes/Atas/Ata1.md
        - 17/02/2022: Modelagem/Reunioes/Atas/Ata2.md
      - Sprint:
        - Planejamento: Modelagem/Reunioes/Sprint/Planejamento.md
        - Revisão: Modelagem/Reunioes/Sprint/Revisao.md
    - Apresentação: Modelagem/Apresentacao.md
  - Padrões de projeto:
    - GRASPs: PadroesDeProjeto/GRASPs/GRASPs.md
    - GOFs: PadroesDeProjeto/GOFs/GOFs.md
    - Padrões Extras: PadroesDeProjeto/PadroesExtras/PadroesExtras.md
    - Iniciativas extras: 
      - Guia de estilo: PadroesDeProjeto/IE/GuiaDeEstilo.md
    - Reuniões:
      - Atas:
        - 11/03/2022: PadroesDeProjeto/Reunioes/Atas/Ata1.md
      - Sprint:
        - Planejamento: PadroesDeProjeto/Reunioes/Sprint/Planejamento.md
        - Revisão: PadroesDeProjeto/Reunioes/Sprint/Revisao.md
    - Apresentação: PadroesDeProjeto/Apresentacao.md